// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: hKULxbku7aAVgz4QBDxfRd
// Component: AugnnAEu1k
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_startup_landing_page.module.css"; // plasmic-import: hKULxbku7aAVgz4QBDxfRd/projectcss
import sty from "./PlasmicMyNewComponent.module.css"; // plasmic-import: AugnnAEu1k/css

export type PlasmicMyNewComponent__VariantMembers = {
  unnamedVariant: "unnamedVariant";
};

export type PlasmicMyNewComponent__VariantsArgs = {
  unnamedVariant?: SingleBooleanChoiceArg<"unnamedVariant">;
};

type VariantPropType = keyof PlasmicMyNewComponent__VariantsArgs;
export const PlasmicMyNewComponent__VariantProps = new Array<VariantPropType>(
  "unnamedVariant"
);

export type PlasmicMyNewComponent__ArgsType = {};
type ArgPropType = keyof PlasmicMyNewComponent__ArgsType;
export const PlasmicMyNewComponent__ArgProps = new Array<ArgPropType>();

export type PlasmicMyNewComponent__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMyNewComponentProps {
  unnamedVariant?: SingleBooleanChoiceArg<"unnamedVariant">;
  className?: string;
}

function PlasmicMyNewComponent__RenderFunc(props: {
  variants: PlasmicMyNewComponent__VariantsArgs;
  args: PlasmicMyNewComponent__ArgsType;
  overrides: PlasmicMyNewComponent__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMyNewComponent__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMyNewComponent__VariantsArgs;
    args?: PlasmicMyNewComponent__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicMyNewComponent__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicMyNewComponent__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMyNewComponent__ArgProps,
      internalVariantPropNames: PlasmicMyNewComponent__VariantProps
    });

    return PlasmicMyNewComponent__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMyNewComponent";
  } else {
    func.displayName = `PlasmicMyNewComponent.${nodeName}`;
  }
  return func;
}

export const PlasmicMyNewComponent = Object.assign(
  // Top-level PlasmicMyNewComponent renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMyNewComponent
    internalVariantProps: PlasmicMyNewComponent__VariantProps,
    internalArgProps: PlasmicMyNewComponent__ArgProps
  }
);

export default PlasmicMyNewComponent;
/* prettier-ignore-end */
